### PR TITLE
PWA-2447: quick port of missing Commerce features/coverage table

### PR DESCRIPTION
**Pull request by bdenham**
## Description

This PR provides a **quick-and-dirty port** of the HTML output from the old Jekyll-based PWA Studio docs site. The HTML for this table will soon be replaced with an interactive, sortable React table component that we can use for all tables in the documentation.

## Related Issue

This topic cannot currently be accessed in the old PWA docs site because of the redirections applied.

## Motivation and Context

The quick-and-dirty approach gets the missing table out there quickly, and gives me some more time to create a React table component that can be reused throughout the documentation.

## How Has This Been Tested?

Generated a staging build here: 

## Screenshots (if appropriate):

Works fine on mobile devices and desktops.

image

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Comment by jeff-matthews** [comment]
Definitely interested in what you come up with here @bdenham and how we might be able to leverage it for the public roadmap: https://devdocs.magento.com/release/roadmap.html.

**Review by jcalcaben — APPROVED** [review]
Can confirm, this is **quick-and-dirty** 😅 

I'm assuming you just copy and pasted the HTML from the page to get the content.

**Comment by bdenham** [comment]
@jcalcaben Yep! :) I had to make a few css tweaks. But yeah, this gets it out there so I can continue to create a solid React table with all the features interactive sorting features and data feeds from json and/or yml files.

**Comment by bdenham** [comment]
> Definitely interested in what you come up with here @bdenham and how we might be able to leverage it for the public roadmap: https://devdocs.magento.com/release/roadmap.html.

@jeff-matthews Yeah, for sure. That's why I put this out there for the short term — to buy me time to do a thorough table component that caters to our conversion needs for porting over our jekyll-based tables.

**Pull request merged**
